import { motion } from 'framer-motion';
import { useLocation, useNavigate } from 'react-router-dom';
import jsPDF from 'jspdf';

function Dashboard() {
  const { state } = useLocation();
  const navigate = useNavigate();

  const data = state || {
    name: 'Koushik',
    age: 20,
    gender: 'Male',
    height: 170,
    weight: 60,
    bmi: 20.8,
    bmiStatus: 'Healthy',
    dosha: 'Kapha',
  };

  const calories =
    data.gender === 'Male'
      ? Math.round(data.weight * 30)
      : Math.round(data.weight * 28);

  const now = new Date();

  const greeting =
    now.getHours() < 12
      ? 'Good Morning ☀️'
      : now.getHours() < 18
      ? 'Good Afternoon 🌤️'
      : 'Good Evening 🌙';

  const date = now.toLocaleDateString('en-IN', {
    weekday: 'long',
    day: 'numeric',
    month: 'long',
    year: 'numeric',
  });

  const time = now.toLocaleTimeString('en-IN', {
    hour: '2-digit',
    minute: '2-digit',
  });

  /* =========================
     PDF REPORT
  ========================= */

  const downloadReport = () => {
    const doc = new jsPDF();

    const pageWidth = doc.internal.pageSize.getWidth();

    const green = [34, 120, 70];
    const lightGreen = [235, 247, 239];
    const dark = [35, 45, 40];
    const gray = [100, 110, 105];
    const orange = [220, 130, 45];

    const reportDate = new Date().toLocaleDateString('en-IN', {
      weekday: 'long',
      day: 'numeric',
      month: 'long',
      year: 'numeric',
    });

    const reportTime = new Date().toLocaleTimeString('en-IN', {
      hour: '2-digit',
      minute: '2-digit',
    });

    /* Header */

    doc.setFillColor(...green);
    doc.rect(0, 0, pageWidth, 43, 'F');

    doc.setTextColor(255, 255, 255);
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(24);
    doc.text('AyurVeda AI', 18, 18);

    doc.setFont('helvetica', 'normal');
    doc.setFontSize(10);
    doc.text('Personal Wellness Report', 18, 27);

    doc.setFontSize(9);
    doc.text(reportDate, pageWidth - 18, 17, {
      align: 'right',
    });

    doc.text(`${reportTime} • IST`, pageWidth - 18, 25, {
      align: 'right',
    });

    /* Title */

    doc.setTextColor(...dark);
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(20);
    doc.text('Health & Wellness Overview', 18, 59);

    doc.setFont('helvetica', 'normal');
    doc.setFontSize(10);
    doc.setTextColor(...gray);

    doc.text(
      'A personalized wellness summary generated by AyurVeda AI.',
      18,
      67
    );

    /* Profile */

    doc.setFillColor(...lightGreen);

    doc.roundedRect(
      18,
      77,
      pageWidth - 36,
      50,
      5,
      5,
      'F'
    );

    doc.setTextColor(...green);
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(11);
    doc.text('PROFILE', 26, 89);

    doc.setTextColor(...dark);
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(10);

    doc.text(`Name: ${data.name}`, 26, 100);
    doc.text(`Age: ${data.age}`, 26, 110);
    doc.text(`Gender: ${data.gender}`, 26, 120);
    doc.text(`Height: ${data.height} cm`, 110, 100);
    doc.text(`Weight: ${data.weight} kg`, 110, 110);

    /* Health cards */

    const cardY = 140;
    const cardWidth = 52;
    const cardHeight = 44;
    const gap = 7;

    doc.setFillColor(246, 251, 248);

    doc.roundedRect(
      18,
      cardY,
      cardWidth,
      cardHeight,
      4,
      4,
      'F'
    );

    doc.setTextColor(...green);
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(9);
    doc.text('BMI', 25, cardY + 11);

    doc.setTextColor(...dark);
    doc.setFontSize(19);
    doc.text(String(data.bmi), 25, cardY + 29);

    doc.setTextColor(...gray);
    doc.setFontSize(8);
    doc.text(String(data.bmiStatus), 25, cardY + 37);

    const doshaX = 18 + cardWidth + gap;

    doc.setFillColor(246, 251, 248);

    doc.roundedRect(
      doshaX,
      cardY,
      cardWidth,
      cardHeight,
      4,
      4,
      'F'
    );

    doc.setTextColor(...green);
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(8);
    doc.text('DOMINANT DOSHA', doshaX + 7, cardY + 11);

    doc.setTextColor(...dark);
    doc.setFontSize(18);
    doc.text(String(data.dosha), doshaX + 7, cardY + 29);

    doc.setTextColor(...gray);
    doc.setFontSize(8);
    doc.text('Wellness profile', doshaX + 7, cardY + 37);

    const caloriesX = doshaX + cardWidth + gap;

    doc.setFillColor(255, 248, 239);

    doc.roundedRect(
      caloriesX,
      cardY,
      cardWidth,
      cardHeight,
      4,
      4,
      'F'
    );

    doc.setTextColor(...orange);
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(8);
    doc.text('DAILY CALORIES', caloriesX + 7, cardY + 11);

    doc.setTextColor(...dark);
    doc.setFontSize(18);
    doc.text(String(calories), caloriesX + 7, cardY + 29);

    doc.setTextColor(...gray);
    doc.setFontSize(8);
    doc.text('Estimated intake', caloriesX + 7, cardY + 37);

    /* Wellness */

    doc.setFillColor(...lightGreen);

    doc.roundedRect(
      18,
      196,
      pageWidth - 36,
      44,
      5,
      5,
      'F'
    );

    doc.setTextColor(...green);
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(12);
    doc.text("TODAY'S WELLNESS SCORE", 26, 209);

    doc.setTextColor(...dark);
    doc.setFontSize(17);

    doc.text('88 / 100', pageWidth - 26, 209, {
      align: 'right',
    });

    doc.setFillColor(210, 225, 215);

    doc.roundedRect(
      26,
      217,
      pageWidth - 52,
      6,
      3,
      3,
      'F'
    );

    doc.setFillColor(...green);

    doc.roundedRect(
      26,
      217,
      (pageWidth - 52) * 0.88,
      6,
      3,
      3,
      'F'
    );

    doc.setTextColor(...gray);
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(8);

    doc.text(
      'Maintain consistent sleep, nutrition, hydration and daily movement.',
      26,
      234
    );

    /* Recommendations */

    doc.setTextColor(...dark);
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(14);
    doc.text('Lifestyle Recommendations', 18, 249);

    const tips = [
      'Stay hydrated throughout the day.',
      'Include balanced and nutritious meals.',
      'Aim for regular daily physical activity.',
      'Maintain a consistent sleep schedule.',
      'Choose meals according to your individual wellness needs.',
    ];

    let leftY = 262;

    tips.slice(0, 3).forEach((tip) => {
      doc.setFillColor(...green);
      doc.circle(23, leftY - 2, 1.5, 'F');

      doc.setTextColor(...dark);
      doc.setFont('helvetica', 'normal');
      doc.setFontSize(8.5);
      doc.text(tip, 30, leftY);

      leftY += 9;
    });

    let rightY = 262;

    tips.slice(3).forEach((tip) => {
      doc.setFillColor(...green);
      doc.circle(23, rightY - 2, 1.5, 'F');

      doc.setTextColor(...dark);
      doc.setFont('helvetica', 'normal');
      doc.setFontSize(8.5);

      const wrapped = doc.splitTextToSize(tip, 65);

      doc.text(wrapped, 30, rightY);

      rightY += 13;
    });

    /* Footer */

    doc.setDrawColor(220, 225, 222);

    doc.line(
      18,
      282,
      pageWidth - 18,
      282
    );

    doc.setTextColor(...gray);
    doc.setFontSize(7.5);

    doc.text(
      'AyurVeda AI • Personal Wellness Assistant',
      18,
      291
    );

    doc.text(
      'For general wellness information only.',
      pageWidth - 18,
      291,
      {
        align: 'right',
      }
    );

    doc.save('AyurVeda_AI_Wellness_Report.pdf');
  };

  /* =========================
     NAVIGATION
  ========================= */

  const open = (path) => {
    navigate(path, {
      state: data,
    });
  };

  return (
    <motion.div
      initial={{ opacity: 0 }}
      animate={{ opacity: 1 }}
      className="min-h-screen bg-[#0b0f0d] px-4 pb-16 pt-24 text-white sm:px-6 md:px-10"
    >
      <div className="mx-auto max-w-7xl">

        {/* TOP HEADER */}

        <div className="mb-8 flex flex-col gap-5 md:flex-row md:items-center md:justify-between">

          <div className="flex items-center gap-3">

            <div className="flex h-12 w-12 items-center justify-center rounded-2xl border border-green-500/15 bg-[#141b17] text-2xl">
              🌿
            </div>

            <div>
              <h1 className="text-2xl font-bold text-white sm:text-3xl">
                AyurVeda AI
              </h1>

              <p className="text-sm text-gray-500">
                Your personal wellness companion
              </p>
            </div>

          </div>

          <div className="text-left md:text-right">

            <p className="text-lg font-semibold text-green-400">
              {greeting}, {data.name}
            </p>

            <p className="mt-1 text-sm text-gray-500">
              {date} • {time} IST
            </p>

          </div>

        </div>


        {/* WELCOME CARD */}

        <div className="mb-8 overflow-hidden rounded-[28px] border border-gray-800 bg-[#121815] p-6 shadow-xl sm:p-8">

          <div className="max-w-2xl">

            <div className="mb-3 inline-flex items-center rounded-full border border-green-500/15 bg-green-500/5 px-3 py-1 text-xs font-semibold uppercase tracking-wider text-green-400">
              Your wellness space
            </div>

            <h2 className="text-2xl font-bold leading-tight sm:text-4xl">
              Understand your health.
              <br />

              <span className="text-green-400">
                Take better care of yourself.
              </span>
            </h2>

            <p className="mt-4 max-w-xl text-sm leading-6 text-gray-400 sm:text-base">
              Explore your wellness profile, talk with AI, scan food,
              and generate your personal health report.
            </p>

          </div>

        </div>


        {/* WELLNESS SNAPSHOT */}

        <div className="mb-10">

          <div className="mb-5 flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between">

            <div>

              <h2 className="text-xl font-bold text-white">
                Wellness Snapshot
              </h2>

              <p className="mt-1 text-sm text-gray-500">
                A quick look at your current wellness profile
              </p>

            </div>

            <div className="flex w-fit items-center gap-2 rounded-full border border-green-500/15 bg-[#121815] px-3 py-1.5 text-xs font-semibold text-green-400">
              <span className="h-2 w-2 rounded-full bg-green-400" />
              Profile Active
            </div>

          </div>


          <div className="grid gap-4 md:grid-cols-3">

            {/* BMI */}

            <SnapshotCard
              icon="⚖️"
              title="Body Mass Index"
              value={data.bmi}
              subtitle="BMI value"
              status={data.bmiStatus}
              statusType="green"
            />


            {/* DOSHA */}

            <SnapshotCard
              icon="🌿"
              title="Dominant Dosha"
              value={data.dosha}
              subtitle="Ayurvedic profile"
              status="Dominant"
              statusType="green"
            />


            {/* CALORIES */}

            <SnapshotCard
              icon="🔥"
              title="Daily Calories"
              value={`${calories} kcal`}
              subtitle="Estimated daily requirement"
              status="Daily target"
              statusType="orange"
            />

          </div>

        </div>


        {/* MAIN ACTIONS */}

        <div className="mb-10">

          <div className="mb-5">

            <h2 className="text-2xl font-bold text-white">
              What would you like to do?
            </h2>

            <p className="mt-1 text-sm text-gray-500">
              Choose a wellness tool to get started
            </p>

          </div>


          <div className="grid gap-4 md:grid-cols-2">

            <ActionCard
              icon="🤖"
              title="AI Chat"
              description="Ask questions about Ayurveda, nutrition, Doshas and healthy living."
              action="Start Chat"
              onClick={() => open('/aichat')}
              featured
            />

            <ActionCard
              icon="🎙️"
              title="Voice AI"
              description="Speak naturally and receive personalized wellness guidance."
              action="Start Speaking"
              onClick={() => open('/voice-ai')}
            />

            <ActionCard
              icon="🍎"
              title="Food Scanner"
              description="Scan your food and explore nutritional and Ayurvedic information."
              action="Scan Food"
              onClick={() => open('/food-scanner')}
            />

            <ActionCard
              icon="📄"
              title="Health Report"
              description="Create a professional PDF report containing your wellness summary."
              action="Download Report"
              onClick={downloadReport}
            />

          </div>

        </div>


        {/* QUICK TOOLS */}

        <div>

          <div className="mb-5">

            <h2 className="text-xl font-bold text-white">
              Quick Tools
            </h2>

            <p className="mt-1 text-sm text-gray-500">
              More ways to explore your wellness
            </p>

          </div>


          <div className="grid gap-4 sm:grid-cols-2 md:grid-cols-3">

            <QuickTool
              icon="⚖️"
              title="BMI Calculator"
              description="Check your body mass index"
              onClick={() => open('/bmi')}
            />

            <QuickTool
              icon="🌿"
              title="Dosha Analysis"
              description="Explore your Ayurvedic profile"
              onClick={() => open('/dosha')}
            />

            <QuickTool
              icon="💡"
              title="Wellness Tips"
              description="Discover healthy lifestyle ideas"
              onClick={() => open('/aichat')}
            />

          </div>

        </div>


        {/* DISCLAIMER */}

        <div className="mt-10 rounded-2xl border border-gray-800 bg-[#101512] p-4 text-center">

          <p className="text-xs leading-5 text-gray-500">
            AyurVeda AI provides general wellness information and does not
            replace professional medical advice.
          </p>

        </div>

      </div>

    </motion.div>
  );
}


/* =====================================================
   SNAPSHOT CARD
===================================================== */

function SnapshotCard({
  icon,
  title,
  value,
  subtitle,
  status,
  statusType = 'green',
}) {
  const isOrange = statusType === 'orange';

  return (
    <motion.div
      whileHover={{ y: -3 }}
      className={`rounded-2xl border bg-[#121815] p-5 shadow-lg transition ${
        isOrange
          ? 'border-orange-500/10 hover:border-orange-500/25'
          : 'border-gray-800 hover:border-green-500/20'
      }`}
    >

      <div className="flex items-start justify-between gap-4">

        <div
          className={`flex h-11 w-11 shrink-0 items-center justify-center rounded-xl text-xl ${
            isOrange
              ? 'bg-orange-500/10'
              : 'bg-green-500/10'
          }`}
        >
          {icon}
        </div>

        <div
          className={`flex items-center gap-1.5 rounded-full px-2.5 py-1 text-[10px] font-semibold ${
            isOrange
              ? 'bg-orange-500/10 text-orange-400'
              : 'bg-green-500/10 text-green-400'
          }`}
        >
          <span
            className={`h-1.5 w-1.5 rounded-full ${
              isOrange ? 'bg-orange-400' : 'bg-green-400'
            }`}
          />

          {status}
        </div>

      </div>


      <div className="mt-5">

        <p className="text-sm font-medium text-gray-500">
          {title}
        </p>

        <p
          className={`mt-1 text-2xl font-bold ${
            isOrange
              ? 'text-orange-400'
              : 'text-white'
          }`}
        >
          {value}
        </p>

        <p className="mt-1 text-xs text-gray-600">
          {subtitle}
        </p>

      </div>

    </motion.div>
  );
}


/* =====================================================
   MAIN ACTION CARD
===================================================== */

function ActionCard({
  icon,
  title,
  description,
  action,
  onClick,
  featured = false,
}) {
  return (
    <motion.button
      whileHover={{ y: -4 }}
      whileTap={{ scale: 0.99 }}
      onClick={onClick}
      className={`group relative overflow-hidden rounded-[24px] border p-6 text-left shadow-lg transition sm:p-7 ${
        featured
          ? 'border-green-500/20 bg-[#121a15] hover:border-green-400/35'
          : 'border-gray-800 bg-[#121815] hover:border-gray-700 hover:bg-[#151c18]'
      }`}
    >

      {featured && (
        <div className="absolute right-5 top-5 rounded-full border border-green-500/15 bg-green-500/5 px-3 py-1 text-[10px] font-bold uppercase tracking-wider text-green-400">
          AI Assistant
        </div>
      )}


      <div className="flex items-start justify-between gap-4">

        <div className="flex h-13 w-13 items-center justify-center rounded-2xl bg-green-500/10 text-3xl transition group-hover:scale-105">
          {icon}
        </div>

        <span className="text-2xl text-gray-700 transition group-hover:translate-x-1 group-hover:text-green-400">
          →
        </span>

      </div>


      <h3 className="mt-6 text-2xl font-bold text-white">
        {title}
      </h3>

      <p className="mt-2 max-w-md text-sm leading-6 text-gray-400">
        {description}
      </p>

      <div className="mt-6 inline-flex items-center gap-2 text-sm font-semibold text-green-400">
        {action}
        <span>→</span>
      </div>

    </motion.button>
  );
}


/* =====================================================
   QUICK TOOL
===================================================== */

function QuickTool({
  icon,
  title,
  description,
  onClick,
}) {
  return (
    <motion.button
      whileHover={{ y: -3 }}
      whileTap={{ scale: 0.98 }}
      onClick={onClick}
      className="flex items-center gap-4 rounded-2xl border border-gray-800 bg-[#121815] p-5 text-left transition hover:border-green-500/20 hover:bg-[#151c18]"
    >

      <div className="flex h-11 w-11 shrink-0 items-center justify-center rounded-xl bg-green-500/10 text-xl">
        {icon}
      </div>

      <div className="min-w-0 flex-1">

        <h3 className="font-semibold text-white">
          {title}
        </h3>

        <p className="mt-1 text-xs text-gray-500">
          {description}
        </p>

      </div>

      <span className="text-gray-600 transition group-hover:text-green-400">
        →
      </span>

    </motion.button>
  );
}

export default Dashboard;